### ISSUE TITLE
Mostrar menos linhas no sigadocker logs

### ISSUE THREAD

**Issue by kmacedovarela** [AndDeluiz/siga-docker#11]
Ao executar sigadocker logs, é exibido todo o console.log que pode ser muito grande e levar mais de 5 minutos para terminar de exibir todo o texto. Seria interessante limitar a exibição a algumas linhas, talvez 100 ou 200.

**Comment by AndDeluiz** [comment]
Adicionada opção de somente exibir um número determinado de linhas do log. O default de exibição ficou em 100 linhas, caso o usuário não informe nada.
