### ISSUE TITLE
Remover deploys da imagem

### ISSUE THREAD

**Issue by kmacedovarela** [AndDeluiz/siga-docker#3]
Remover os deploys da imagem inicial, deixar configurado aPENAS:

ojdbc6.jar
ckeditor.java

**Comment by AndDeluiz** [comment]
A imagem estava configurada para fazer deploy pela pasta deployments do sigadoc. Esta configuração inicial existia conforme acerto para que fosse feito um depoloy automático das apps ao iniciar o contêiner.
Com as novas demandas e acertos com o cliente, não é mais necessária essa configuração. Assim, foi removida a pasta deployments e os .war existentes.
Gerada imagem com ID build-00011 com as devidas correções.
