### ISSUE TITLE
Metadados do build?

### ISSUE THREAD

**Issue by kmacedovarela** [AndDeluiz/siga-docker#6]
Verificar se é possível acrescentar comentario no build.
Ex:

 sigaDocker build app "Adicionando modulo xyz"

**Comment by AndDeluiz** [comment]
Na versão utilizada não existe essa possibilidade diretamente, apesar de existir um campo nos metadados da imagem que poderia ser utilizado.
Podemos chegar a uma solução de contorno utilizando a diretiva MAINTAINER, uma variável de ambiente na imagem ou a inclusão de um arquivo texto.
